### ISSUE TITLE
微擎模板修改

### ISSUE THREAD

**Issue by lutaoact** [genfengxue/gale_home#2]
这是内容页：
http://weiqing.genfengxue.com/app/index.php?c=site&a=site&do=detail&id=4&i=2

需求：
1 给内容页最下边加上我们的首页链接和返回资源汇总页的链接
网址分别是：
www.genfengxue.com
http://weiqing.genfengxue.com/app/index.php?i=2&c=entry&id=11&do=detail&m=news&wxref=mp.weixin.qq.com#wechat_redirect

2 把内容页的大黑条去掉

**Comment by ouzhenkun** [comment]
@lutaoact 已去
